### ISSUE TITLE
bug: optifine Fullscreen YES/NO option interferes with Search feature in Thaumonomicon

### ISSUE THREAD

**Issue by ghost** [BluSunrize/WitchingGadgets#100]
I can't explain it exactly how or why but having Fullscreen to NO aka fake window mode in Optifine prevents the search bar for being use-able or click-able. 

So far I have noticed I either have to have 
Fullscreen: YES
Resolution: Default 

OR 
Fullscreen: NO
Resolution ( here I put my native screen resolution)

and it MIGHT work but  only about 50% of the time

I have to go back and forth and restart the game a couple of times if I want the feature usable.

Reproduce-able : always

**Comment by BluSunrize** [comment]
I don't fix bugs caused by optifine, because it's a terrible mod.
