### ISSUE TITLE
Developed Iconographs

### ISSUE THREAD

**Issue by Shahelion** [BluSunrize/WitchingGadgets#103]
I'm not sure which behaviour is intended.

If I have the aspects to understand the mob, it does not consume the iconograph.
If I do NOT have the aspects, it doesn't give the aspects of the mob to me but still consumes it.

**Comment by Shahelion** [comment]
Status?

**Comment by BluSunrize** [comment]
The last version of WG was released 6 years ago. I have no plans to maintain it currently.
