### ISSUE TITLE
Ring of the Covetous coin recept

### ISSUE THREAD

**Issue by nailfor** [BluSunrize/WitchingGadgets#107]
I'm installed the mod project red in my server(base, compat, integration, lighting), this mod registred silver ignot, but without silver ore. Now i'm can't infuse Covetous Coin, because there is not silver ingot

in file WGResearch i'm found

ItemStack stack_ingot = !OreDictionary.getOres("ingotSilver").isEmpty()?OreDictionary.getOres("ingotSilver").get(0): new ItemStack(Items.iron_ingot);

i think that should be getOres("ingotOres")I'm install project red mod in my server, this mod registred silver ignot, but without silver ore. 
ItemStack stack_ingot = !OreDictionary.getOres("ingotSilver").isEmpty()?OreDictionary.getOres("ingotSilver").get(0): new ItemStack(Items.iron_ingot);

**Comment by BluSunrize** [comment]
Well tell ProjectRed to fix their mod then. If they add an ingot that isn't obtainable it shouldn't be added to the OreDict. That's their fault, not mine.
