### ISSUE TITLE
[Bug]Ring of Covetous Coin doesn't work

### ISSUE THREAD

**Issue by DarkLight66** [BluSunrize/WitchingGadgets#11]
I tried using a diamond pick with no enchants and covetous coin on a stack of coal ore with no drop increase, then i tried enchanting the pick with fortune 1 and mining another stack of coal ore and none of them dropped more than 2 coal. I have "Allow Enchantment modifications" set to true in the config.

**Comment by BluSunrize** [comment]
Fixed in 1.1.0
