### ISSUE TITLE
[Feature Request] - Boolean for turning off the integrated search or for the

### ISSUE THREAD

**Issue by chaos234** [BluSunrize/WitchingGadgets#114]
Is it possible to add a config boolean to disable the search feature? It's nice but actually it spams horrible in the console :/.

**Comment by KryptonCaptain** [comment]
Occasionally, [someone listens](https://github.com/KryptonCaptain/WitchingGadgets/releases/tag/1.2.2).
Even if it is 6 months later, and you might be playing on another version.

**Comment by BluSunrize** [comment]
Could have...you know...asked me?
Not every code visible on Git is public domain.

**Comment by chaos234** [comment]
At first thanks for those fixes but please, @KryptonCaptain , talk to/with @BluSunrize so that he can merge your fixes. Will be glad if this will be merged and officially released :).

**Comment by BluSunrize** [comment]
Thing is, WG is not being worked on anymore. Development on this mod has ceased, as has my interest in developing for Minecraft 1.7.10.
Thing is that that still does not give permission for other people to fork and release stuff without my permission. There is still such a thing as intellectual property and licensing. While I don't mind too much with this one (as long as it's unmonetized), as I consider the mod to be done, it's still a matter of decency and politeness to ask a developer before you fork and release their code.

**Comment by chaos234** [comment]
True words @BluSunrize.

Well, what should I do know? Did you checked the changed code or is it ok if I am going to use his fix?
I hope that you can finde a way so that it's ok if he releases fixes to your mod as long as he mentions
you in your prefered way.


Am 17.01.2017 22:10:06 schrieb BluSunrize <notifications@github.com>:
Thing is, WG is not being worked on anymore. Development on this mod has ceased, as has my interest in developing for Minecraft 1.7.10.
Thing is that that still does not give permission for other people to fork and release stuff without my permission. There is still such a thing as intellectual property and licensing. While I don't mind too much with this one (as long as it's unmonetized), as I consider the mod to be done, it's still a matter of decency and politeness to ask a developer before you fork and release their code.

**Comment by KryptonCaptain** [comment]
![image](https://cloud.githubusercontent.com/assets/8790829/22046882/a727de56-dd77-11e6-9a8d-0189ee9a710a.png)
Seems fine to me.
It was by your own admission, a dead mod. The fork was only intended to be used by a small group of people anyway, and was mostly just some small bugfixes and tweaks.

**Comment by chaos234** [comment]
@KryptonCaptain - Thanks for adding this, now some console spam on the client side is gone away :). I hope that you'll make other bugfixes if you have that time.
