### ISSUE TITLE
[Feature] Request 

### ISSUE THREAD

**Issue by EndermanParty** [BluSunrize/WitchingGadgets#12]
A new form of Abacus - or an upgraded form that allows you to see the primal centivis amount within the node. I am lazy and I don't want to do math.

**Comment by EndermanParty** [comment]
I should add this for a node that is not Electric just yet.

**Comment by BluSunrize** [comment]
Naaaah, that's just easy mode =P
Besides, if the Node has a certain modifier, the resulting energized one can turn out a bit random.

**Comment by EndermanParty** [comment]
Alright, Thanks. I love your mods. I loved Travelers Gear and now you have a great addon to go with it. At some point I'll come up with another request. :P
