### ISSUE TITLE
Crash with TC 4.2.3.5

### ISSUE THREAD

**Issue by Xorbah** [BluSunrize/WitchingGadgets#122]
Just seems not to want to play well with TC itself? A bit confused.

[crash-2017-06-15_20.48.29-client.txt](https://github.com/BluSunrize/WitchingGadgets/files/1079528/crash-2017-06-15_20.48.29-client.txt)

**Comment by BluSunrize** [comment]
That's not a WG error. You're trying to use "TCBotaniaExoflame", but you don't have Botania installed.
