### ISSUE TITLE
light glitch

### ISSUE THREAD

**Issue by ghost** [BluSunrize/WitchingGadgets#125]
This mod has a weird light glitch issue. If you look at mobs  from a certain direction all mobs lighting is flat without shadows. It may be related to new forge and probably one of the enchantments. I noticed some of the enchantments like unveiling doesn't do anything it may simply interfere with lighting.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/36826319/51064690-f63ab680-15ce-11e9-9af4-0be0af04e3d5.png)
![image](https://user-images.githubusercontent.com/36826319/51064694-fa66d400-15ce-11e9-8bb9-4d9bd0d93309.png)


I been working for a year to figure out what mod is causing this and I  think is this mod in combination with something else not quite sure what probably the JVM version and the forge version.

**Comment by ghost** [comment]
this doesn't happen on openjdk8   but it does happen only with the built in java

**Comment by ky3nets** [comment]
The problem is cause by the Developed Iconographs rendered in the world:
In the point where are you looking at there is a structure from this mod that has the iconographs in item frames that are creating these problems
