### ISSUE TITLE
hi found a duplicate enchantment id from a another mod i hoping for you to work it out together 

### ISSUE THREAD

**Issue by ghost** [BluSunrize/WitchingGadgets#126]
**Brief explanation of the problem**

a duplicate enchantment id 

**Steps to reproduce**

add witching gadgets version and it depences 
https://minecraft.curseforge.com/projects/witching-gadgets/files/2262119

and download this version of matter mega drive
https://minecraft.curseforge.com/projects/matter-megadrive/files/2514503  

**Crash report **
https://github.com/Ionaru/MatterMegadrive/issues/9

[crash-2019-03-12_12.25.35-client.txt](https://github.com/Ionaru/MatterMegadrive/files/2958522/crash-2019-03-12_12.25.35-client.txt)

**Matter Megadrive version** 
https://minecraft.curseforge.com/projects/matter-megadrive/files/2514503

currently getting help from this mod creator
fewizz/NotEnoughIDs#87

**Comment by coolingwalter** [comment]
hi its me crae i would like some fix in the near future it would help a lot

**Comment by BluSunrize** [comment]
There is a config option to change the enchantment ID. Use that to set it to an un-occupied one. Witching Gadgets is no receiving any further updates.

**Comment by coolingwalter** [comment]
ok thanks
