### ISSUE TITLE
Crash on world load/start

### ISSUE THREAD

**Issue by plazia** [BluSunrize/WitchingGadgets#14]
Started a new world to test out your wonderful looking mod
Get a crash with this output from my ATLauncher. No matter how hard I try I can't get your mod to work.

(also I have travellers gear the requisite mod installed.)

http://pastebin.com/7VPfu3AJ

I'm no expert or a programmer so I can't make sense of the output but is it interfering/conflicting with minefactory reloaded?

Thanks,

plazia

**Comment by BluSunrize** [comment]
Yes it is. Disable nugget transmutations in the config.
