### ISSUE TITLE
Nugget transmutation startup crash persists after version 1.1.1

### ISSUE THREAD

**Issue by SotataSota** [BluSunrize/WitchingGadgets#15]
I've already gone ahead and disabled the transmutation setting again, I assume this is what the "possible nullpointer fix" is about so I just feel like it's worth mentioning that it **is** still a problem.

**Comment by BluSunrize** [comment]
I need a crashlog

**Comment by SotataSota** [comment]
http://pastebin.com/EBJPphMy
Had to snip out a bit at the top since the errors were displayed twice (I did check, the two lists were entirely identical) and it was going over the pastebin limit, but hopefully I have everything that's part of the crashing portion of the crashlog there.

Can't actually grab a regular crashlog file because it doesn't crash-to-desktop, it just crashes the internal server when attempting to load or create any world.

**Comment by BluSunrize** [comment]
And you are sure that you have  B:"Enable transmutations"=false in the config? Because those transmutations are the only thing to come to mind that could cause it...

**Comment by SotataSota** [comment]
Ah, no, see I made that change to prevent the crash afterwards.
Was I incorrect in assuming the attempted null pointer fix in 1.1.1 was not to do with this issue?

**Comment by BluSunrize** [comment]
This isn't a NullPointer, this is a StackOverflow =P
The NPE prevention was happening for some people when registering clusters. The fix I added for that was full on guessing, since I couldn't reproduce the error.
