### ISSUE TITLE
Thaumic Stone Extruder doesn't stop when chest is full

### ISSUE THREAD

**Issue by ewsmith** [BluSunrize/WitchingGadgets#17]
The extrude just spits cobble out everywhere when the chest is full.

**Comment by BluSunrize** [comment]
It doesn't for me. What version are you running?

**Comment by ewsmith** [comment]
version 1.1.2
also: the extruder was under a single vanilla chest which was right next to a single trapped chest

**Comment by BluSunrize** [comment]
ah, the "upwards" was the key. Will be fixed in the next version
