### ISSUE TITLE
[Suggestion] Cloak crafting recipes are either incorrect or inconsistant

### ISSUE THREAD

**Issue by SotataSota** [BluSunrize/WitchingGadgets#19]
While I appreciate the idea behind allowing the use of the Traveller's default cloak item, it is significantly cheaper than the cloak item provided by the mod and only works in 3 of the 4 upgraded cloak recipes.
Either the cloak item provided by the mod should be removed, and have the research be an auto-unlocked research showing the crafting recipe for the Traveller's variant, or have all of the ability cloaks provided by the mod require the magical cloak, and _only_ the magical cloak.
It really feels like a mistake the way it is.

On a similar albiet only vaguely related note, can we have a config option to disable the rendering of cloaks? They clip a lot and I dislike how smooth it looks, so an option to make them invisible out of preference would be appreciated.

**Comment by BluSunrize** [comment]
The translucency enchant makes them invisible. And it's not too expensive =P
The cloak thing should already be fixed in the latest version...if it isn't I'm not remembering my own updates correctly, but it'll definitely be in the next release

**Comment by Barhandar** [comment]
Latest WG release, "magical" cloaks except one are still made with Traveller's Gear cloak, not WG's.
