### ISSUE TITLE
Botania Crashing

### ISSUE THREAD

**Issue by Corvorosso** [BluSunrize/WitchingGadgets#20]
i have some issue with botania when witching gadgets is installed

if a spreader with warp lents impact a force relay , the game crash
this does not happen if i remove your mod

this is the crash log
http://pastebin.com/4J88DsMa

ps: sorry for my poor english :P

**Comment by BluSunrize** [comment]
Known issue, due to me packaging the IManaburst from Botania. Will be fixed with the next release
