### ISSUE TITLE
Not a Clue... Textures?

### ISSUE THREAD

**Issue by O13SC3N3** [BluSunrize/WitchingGadgets#22]
This little guy one day just started appearing. Not sure why, Custom Modpack 225 Mods, this never had issue before. Even on new World Creation, or even my server.

http://pastebin.com/26mnQYLB

**Comment by O13SC3N3** [comment]
After some investigating, the error only occurs in the latest forge builds after 1291; they are 1307 and 1340.

**Comment by BluSunrize** [comment]
Oh /now/ it makes sense. Forge versions beyond 1291 are for Minecraft 1.8! You have the wrong Forge! xD

**Comment by BluSunrize** [comment]
I actually take it back, builds beyond 1291 exist, they just don't seem to show as usual Forge builds. I'll look into the matter as best as I can.

**Comment by BluSunrize** [comment]
tentative fix in the upcoming version. Reopen this please if the bug persists in V1.1.3
