### ISSUE TITLE
Crash when scanning a node with Iconograph

### ISSUE THREAD

**Issue by kimfy** [BluSunrize/WitchingGadgets#23]
To reproduce:
1. Scan aura node with a Thaumic Iconograph Box
2. Selecting the used Iconographic Plate will crash you, it might not happen instantly, wait a while, and it did. I successfully reproduced it twice on my server.

It wouldn't let me log in again, it would instantly crash me. Here's a log: [pastebin](http://pastebin.com/VNZvshRB)
Fix: remove Iconographic Plate from inventory using an NBT editor or delete your playerdata file.

**Comment by BluSunrize** [comment]
Unsure on this one, potential fix in the upcomign version. Reopen if this persists in 1.1.3
