### ISSUE TITLE
Memory Leak discovered! WG 1.1.2 Forge 1307

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/WitchingGadgets#24]
Background: After installing this mod we updated Botania and Technomancy. Shortly after we realized there was a huge memory link, upwards of 4-5 extra gigs before we started noticing memory issues. Took out all the mods one at a time, with Witching Gadgets last, and the memory issue disappeared. Attached is the heap space issue and the troubleshooting I had help from Player and Vazkii.

Stats: 4GB assigned to Java, 16GB total system memory, no prior memory-related issues. Typically runs stable at 4GB max, often less. 

http://pastebin.com/TZNi14fP
https://github.com/Vazkii/Botania/issues/676

**Comment by BluSunrize** [comment]
Not sure I can help you with that one, I can't really read actual java crashes. I'm kinda tempted to blame Java8 for it though. Wish Mojang would stop advertising it.

**Comment by Alaberti** [comment]
I have been using it for a few months now but only recently did this become an issue. I wish I could be more helpful, but most of what I have to report is just what I've noticed. Happens even if no blocks are placed or items are used...have any threads or anything in the background that just doesn't hit the garbage collector for some reason?

**Comment by BluSunrize** [comment]
I don't do multithreading in WG (to be perfectly honest, I've never done multithreading in Java ever). I'll do my best to optimize my rendering code I guess and fix all the other Botania related issues that currently exist? Until then I can only tell you to await the next release, due some time next week.

**Comment by Vazkii** [comment]
See line 53. You should keep a singleton for your armor model rather than create a new one every time.
Also, for the love of god please include the package-info.java file for the botania API.

**Comment by BluSunrize** [comment]
IManaBurst gets removed in the next version anyway, to save me the trouble of keeping up with API changes.

**Comment by Vazkii** [comment]
That's exactly why you add the package-info.java file. So you don't have to keep up with API changes.
