### ISSUE TITLE
Breaking elven mana spreader with primordial axe

### ISSUE THREAD

**Issue by echohunter221** [BluSunrize/WitchingGadgets#29]
No idea why this crashes, but it does. And only the elven mana spreader it seems, no other axe I've seen does it. Crash report: http://pastebin.com/Qg4uyyms

**Comment by Alaberti** [comment]
Have you also reported this to Vazkii on the Botania Github?

**Comment by BluSunrize** [comment]
Yeah, @Vazkii is lacking a null check there, though admittedly that tileentity should not be null.
I think I messed up the order of harvestBlock and onBlockHarvested.
I'll check it out.
