### ISSUE TITLE
Rendering Crash

### ISSUE THREAD

**Issue by GreatOrator** [BluSunrize/WitchingGadgets#30]
This crash happens when using v1.1.3 of the mod

http://pastebin.com/ZM1Bh2W7

I am trying to pin down details of what was going on when the crash happened, but was told second hand.

**Comment by BluSunrize** [comment]
Someone, somehow, got their hands on a block with a metadata that should not exist. BlockStoneDevice only goes to 8.

**Comment by GreatOrator** [comment]
I know what you said, but getting more reports of the same crash and a new one.

http://pastebin.com/JvmrDAci - similar to first report

http://pastebin.com/zjupFjce - new one

**Comment by BluSunrize** [comment]
First crash is the same thing and the same error. Did you cheat in something?
Second one is entirely different, you somehow managed to open the inventory of the glove and didn't have the glove selected when closing it. Try not to do that.

**Comment by GreatOrator** [comment]
No cheating in of items as far as I can tell, haven't been able to get that nailed down but trying (could be an item from the HQM book) but considering the number of people playing, could be one-offs.

I'll keep investigating to try to replicate but has been difficult.

The second one happened supposedly with someone just walking along.

**Comment by GreatOrator** [comment]
So update on the second crash...

"they didn't close the inventory before handing it to someone else"

On the first crash...

"the others are happening all over the world when people are exploring, its because he has these little lights that generate in the world and when they generate they crash the player"

**Comment by BluSunrize** [comment]
well the second one is entirely their fault then. >_<

And for the first one, I do not recall generating any "lights". I have absolutely no idea what you're talking about.

**Comment by Alaberti** [comment]
What are all the mods you're running?

**Comment by GreatOrator** [comment]
https://docs.google.com/spreadsheet/ccc?key=0AjZ9KTyFfyeOdHVKbjRVR3hVSk1PSEtodmJ1MTJKUGc#gid=0

Complete list

And the lights were called "glimmering lights"

**Comment by Alaberti** [comment]
Does anyone have the Light spell from Ars Magica 2?
