### ISSUE TITLE
java.lang.NullPointerException: Ticking entity crash caused by steam potion effect(?)

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/WitchingGadgets#32]
Reportd here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2371563-thaumcraft-addon-witching-gadgets?comment=192

CyricV: This crash to desktop happens whenever a player is affected by the Stove's steam affect[sic]

**Comment by BluSunrize** [comment]
hopefully fixed in the next release. Feel free to reopen if it persists.
