### ISSUE TITLE
Can't open traveller's gear abilities menu near other players

### ISSUE THREAD

**Issue by Owlmighty** [BluSunrize/WitchingGadgets#34]
As the title says, no error in the logs or anything i just can't open the radial menu, yes it works if i'm far away from other players.
Should i post this on the traveller's gear issues page as well?
Btw i love the mod, great work!

**Comment by BluSunrize** [comment]
You should have opened this /only/ on the TG page since it's that mod's issue. however, I have no idea what causes this. It seems to be a fairly rare bug and I can't replicate it.

**Comment by Owlmighty** [comment]
Oh ok, i`ll open the issue there then.
