### ISSUE TITLE
Infernal Blast Furnace Bugs

### ISSUE THREAD

**Issue by ElvenChaos** [BluSunrize/WitchingGadgets#37]
I've got two bugs for you.

First and foremost: a crash. When you drop a lot of invalid items into the Blast furnace, it causes a ticking particle exception: http://pastebin.com/RKdC6Ft6 . To reproduce the bug I held a stack of an item in my hand and spammed [Q] into the blast furnace. The crash only happens once you've spammed for about two seconds. To me it looks like it has to do with the "wrong item" lava particles.

Secondly, a minor incompatibility of the IBF and AOBD clusters. When the WG clusters are turned off and AOBD's are used, AOBD clusters are treated as "wrong items" instead of producing three ingots in the IBF. I have not tried flipping the configs around yet (I am about to), it is just your config is much easier to change that option than in AOBD's config, where I have to turn each ore's Thaumcraft option off.

**Comment by BluSunrize** [comment]
first one: I'll look into it.

second one: hmm, interesting, I was under the impression that my furnace was OreDictionary based. I specifically tried it with AOBD and their clusters smelted into three...

**Comment by ElvenChaos** [comment]
To attempt to help narrow down the second bug, I made a separate minecraft instance via MultiMC with fewer mods. I included WG, AOBD, Big Reactors, Thermal Expansion, and TCon.

First time: I let everything be default. WG clusters took precedence, but clusters not covered by WG were generated by AOBD. I tossed in two AOBD clusters. The clusters gave off the "wrong item" effect and then caused the ticking particle crash: http://pastebin.com/WjZUKgt6 .

Second Time:
Afterwards, I changed the configs to disable WG clusters. AOBD generated all clusters. I tossed in AOBD clusters and got the "wrong item" particles. However, I did not get the ticking particle crash. I tried spamming the items as I did in the original problem, but could not re-produce the ticking particle crash with the smaller load-out and config change.

**Comment by BluSunrize** [comment]
what clusters exactly did you toss in? because my support probably does not cover all of them

**Comment by ElvenChaos** [comment]
Initially I tried the Platinum, Aluminum, and Yellorium clusters from AOBD. Reloaded the smaller test pack to be sure, and then tested each cluster. I threw in one cobalt cluster (first cluster) and got ticking particle http://pastebin.com/MEK9xnPZ . Booted back up, did it again and couldn't reproduce the ticking particle. Then I threw in each AOBD cluster (including clusters that would be normally supported by WG, such as cobalt and aluminum) to get the "wrong item" effect. After that, I tossed in each Thaumcraft cluster (this includes clusters thaumcraft generates in response to other mods, i.e. silver and lead) and it worked as intended.

EDIT: Just reduced the testing loud-out to a near-bear-minimum state: Baubles, CCC, AOBD, COFHCore, JourneyMap, Mantle, NEI, TCon, Thaum, Trav Gear, WAILA, WG, Forge 1362.

I still manage to get a Ticking Particle by spamming http://pastebin.com/z5HzaeVz . The AOBD clusters still refuse to triple in the IBF, and the Thaumcraft clusters that the pack generates still DO work (almost false-alarmed silver and lead, which are no longer in the pack).

**Comment by BluSunrize** [comment]
This might be fixed in version 1.1.4 now. Trippling should now be added even if WG clusters are disabled.

**Comment by ElvenChaos** [comment]
I can't test the full suite of AOBD clusters due to the start up crash posted in another issue thread, but with clusters enabled along side AOBD, the AOBD-only clusters are not tripling still. The AOBD-only clusters are Yellorium and Aluminium (another interesting bug, AOBD is registering alumin[i]um and WG is registering aluminum clusters).

EDIT: Ticking particle seems to be fixed, as I just tried my hardest to spam invalid clusters and item in and it wouldn't crash! Thanks for the fix here!

**Comment by BluSunrize** [comment]
Registering stuff as Aluminium might be the 'correct' way to do it, but it's not the 'right' way.
The only mod that registers its ore as aluminium is Tinkers, everyone else uses Aluminum (as does Tinkers, they do both) AOBD (or you, if you did the config) should register for Aluminum to make it work with other mods.
As for Yellorium: I account for Uranium, because seriously, that's what Yellorium is, and afaik BigReactors registers as Uranium by default, unless it's changed in the config.

I will create config option for the next release to allow registering custom names.

**Comment by BluSunrize** [comment]
New release is out!

**Comment by ElvenChaos** [comment]
With the 1.1.4 crash fixed I was able to test the other AOBD ores and verified that they now work. Yellorium and the Allumin[I]um still gave me some problems, but when I added those two names to the list everything worked perfectly.

Thank you for the fixes, and thank you for being on top of the issues!
