### ISSUE TITLE
Missing Cluster

### ISSUE THREAD

**Issue by ElvenChaos** [BluSunrize/WitchingGadgets#38]
With clusters from WG enabled and Big Reactors installed, the Yellorium/Uranium clusters are MIA.

**Comment by BluSunrize** [comment]
That would be because there are no Uranium Clusters in WG.

**Comment by ElvenChaos** [comment]
Sorry, I should have been more specific about this one! There are no Yellorium clusters in WG, but could you add support for that?

**Comment by BluSunrize** [comment]
That's an entirely different matter and a definite maybe.
