### ISSUE TITLE
Botania Cosmetic Override

### ISSUE THREAD

**Issue by Hazado** [BluSunrize/WitchingGadgets#4]
I put the cosmetic override devil tail on a mantle of the raven and instead of the tail I only see the raven cloak.

Not sure if this is working correctly.

**Comment by BluSunrize** [comment]
The cloak is too big, the tail renders below it. Nothing to change about that, I'm not gonna change my cloak render for a single cosmetic item ^^
Also: Try the translucency enchantment. It hides the cloak, but the tail still shows =P
