### ISSUE TITLE
Startup Crash With 1.1.4

### ISSUE THREAD

**Issue by Syer10** [BluSunrize/WitchingGadgets#40]
http://pastebin.com/3kugSrHY

**Comment by psychofad** [comment]
I am also getting this error!

**Comment by ElvenChaos** [comment]
I initially got the error http://pastebin.com/dvZ4P4fQ . I deleted the config to generate a new one and did not get the error after that. Lastly, I changed the config option for clusters to false (as my original config was set that crashed me) and then got the start up crash again.

Setting clusters = false is causing the crash.

**Comment by BluSunrize** [comment]
This will be fixed in Version 1.1.5, due to release today.

**Comment by BluSunrize** [comment]
scratch that, it's already on curse :D
