### ISSUE TITLE
Crash with MFR

### ISSUE THREAD

**Issue by ElvenChaos** [BluSunrize/WitchingGadgets#41]
With the recently released version of MFR, WG causes a crash. More information available at the ticket over on the MFR github https://github.com/skyboy/MineFactoryReloaded/issues/412 and my logs http://pastebin.com/TzsPgfhP (crash is forcing itself to available, so I don't have just a crash report -- just my latest.log).

EDIT: WG currently does work with the previous version of MFR, but the current release of MFR is currently not compatible due to this crash.

**Comment by BluSunrize** [comment]
Disable nugget transmutation in the config
