### ISSUE TITLE
[Bug]Hungry bag stacking wispy essences rewardles of aspect.

### ISSUE THREAD

**Issue by DarkLight66** [BluSunrize/WitchingGadgets#42]
While having a hungry bag with a an ignis wispy essence for example, and you pick up an aqua wispy essence, the aqua one will turn into a ignis one and stack with the one you already have.

**Comment by BluSunrize** [comment]
Oh wow, thanks for the heads up! I'll fix that in the next version ^^

**Comment by BluSunrize** [comment]
Reopen if this persists
