### ISSUE TITLE
Java.lang.NoSuchFieldException: c 

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/WitchingGadgets#44]
Just a strange error I'm seeing in the console from time to time. Doesn't seem to crash anything, working on the 1.15 version, forge 1307. I am told to tell you that I am using Fastcraft. Seems related to flux gloo, is this something I should also address with @Azanor?

---

[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoSuchFieldException: c
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.Class.getDeclaredField(Unknown Source)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at witchinggadgets.asm.WGCoreTransformer.living_onPotionApplied(WGCoreTransformer.java:325)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityLivingBase.func_70670_a(EntityLivingBase.java:690)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:642)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at thaumcraft.common.blocks.BlockFluxGoo.func_149670_a(BlockFluxGoo.java:81)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at thaumcraft.common.entities.monster.EntityTaintSpore.func_70091_d(EntityTaintSpore.java:118)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1490)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at thaumcraft.common.entities.monster.EntityTaintSpore.func_70071_h_(EntityTaintSpore.java:156)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72866_a(World.java:2070)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72870_g(World.java:2034)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at WorldServerOF.func_72870_g(WorldServerOF.java:347)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72939_s(World.java:1887)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by BluSunrize** [comment]
No need to bother Azanor with this, that seems to be related to my primordial armor reducing warp effect intensity. Apparently my coremod broke somewhere. 
Will look into it.

**Comment by Alaberti** [comment]
Haven't seen this in awhile sooo.
