### ISSUE TITLE
Thaumcraft structure World Generation

### ISSUE THREAD

**Issue by bookerthegeek** [BluSunrize/WitchingGadgets#46]
Hello, discovered your mod on our Regrowth server. Wonderful mod.

We did discover one thing thou, It seams that your config option to add to the list of blocks that Thaumcraft structures can spawn on is not working correctly.

How I tested after adding cracked sand to the config:
1. Created a flat world made out of stone with a world height of 70, Structures Spawned
2. Created a flat world made out of Cracked Sand with a world height of 70, Structures do not spawn

Please feel free to ask if you need anymore information.

**Comment by BluSunrize** [comment]
Are you sure you added it correctly?

And even so, not much I can do, really. I'm already hacking Thaumcraft as is for this to work at all. I would have to rewrite their worldgen entirely to make precise changes, and that's not happening.

**Comment by bookerthegeek** [comment]
This is the line in the configs:
"ExtrabiomesXL:terrain_blocks2"

Without the ""

**Comment by BluSunrize** [comment]
yeah, that should theoretically works. The fact that it doesn't, I blame TC for.
