### ISSUE TITLE
Crystal Capsules are broken in a couple ways

### ISSUE THREAD

**Issue by Azutte** [BluSunrize/WitchingGadgets#49]
I first saw it with Vishroom Stew from Automagy, I was attempting to use lava capsules. The Automagy dev [saw a capsule incorrectly output](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2125369-tc4-addon-automagy-automation-and-logistics-v0-22?comment=717) Flux Goo, and another user in that topic also saw Vishroom Stew.

Today, I actually tried investigating more than I had the first time. I tried giving myself a bunch of different capsules so I could see what each one might theoretically put into a tank. The first one I used was "molten shiny", which put "molten shiny" into the tank -- but then so did everything else.

I thought maybe it might be world-specific, so I made another world and tried the same experiment. Everything output molten shiny into a tank.

I then thought, maybe it was per instance-of-you-loading-the-client, so I restarted my client. Still molten shiny! It's also not "the first capsule you use in the world". After the first time, I made sure to NOT use molten shiny first, and even doing lava and non-TiCon fluids still put in molten shiny.
# 

SECONDLY: When you right click on Tinker's Construct tanks (seared tank, seared window, seared glass) it puts 1000mB into the tank, and 1000mB out in the world as a fluid block, which proceeds to flow everywhere. I asked #tinkersconstruct if this was even remotely possibly on their end, and mDiyo commented:

[21:08:55] @mDiyo Tinkers' Construct uses standard liquid mechanics. If anything, it's on the Witching Gadgets end.

**Comment by BluSunrize** [comment]
Will be fixed in the next version. Forge's FluidContainerRegistry is stupid and doesn't like NBT data.
