### ISSUE TITLE
Weird crash to menu at world load

### ISSUE THREAD

**Issue by InkDragon** [BluSunrize/WitchingGadgets#5]
I have an issue where when I go to load or create a new world with this mod installed and MFR installed it causes the game to crash back to the title screen.

As it isn't a complete crash a log is not generated.

I can however provide a copy of the minecraft console errors avalible here: https://dl.dropboxusercontent.com/u/41320297/Minecraft/Packs/Tiny/error.txt

If this error doesn't belong here please let me know and I will post it to the correct mod author. As I fear this is likely an interaction between several mods

**Comment by BluSunrize** [comment]
Error is known. Neither me nor Skyboy have any idea as to why it happens, and I can't even reproduce it. I included what I hope might be a fix in the new version, v1.0.3

**Comment by InkDragon** [comment]
Sadly still happens for me. Tested with the latest Witching Gadgets and both the Stable release and latest alpha of MFR. 

Not sure if this will help but this is the environment I am using:
https://www.dropbox.com/sh/7gs196265z8mo89/AAAnUq_cLY28VqscWDi77Ho7a?dl=0

I know it doesn't happen with just TC, MFR, and Witching. It seems to only have an issue when loaded with several different mods.

**Comment by BluSunrize** [comment]
Yeah, I've heard from multiple people :/
I really dunno what's causing it. I couldn't even produce the bug in FTB Infinity which contains a ton of mods...

**Comment by BBoldt** [comment]
I am experiencing this bug as well.

Log: http://paste.atlauncher.com/view/d8e91c18

Modlist (sorry it's long): http://pastebin.com/B7AwaK4f

**Comment by BluSunrize** [comment]
Get the new version, v1.0.4 and in the config, disabled transmutation recipes. This is a temporary fix for now, but it should help.

**Comment by BBoldt** [comment]
That did the trick!
Thanks for the quick solution.

Btw, extra thanks for adding the ability to disable your Thaumcraft ore cluster things, my pack is already set up with AOBD.

**Comment by InkDragon** [comment]
Yup, fixed the issue by disabling transmutations. Thank you!
