### ISSUE TITLE
Wolven Cloak (still) causing crashes when DOT effects applied

### ISSUE THREAD

**Issue by Yoghurt4C** [BluSunrize/WitchingGadgets#50]
When hit by mobs that poison\wither, the game crashes with crash logs like this one
http://pastebin.com/qEu7XjmB

**Comment by Iapyx** [comment]
This was real fun to find the hard way during a Gaia II fight... So yeah, reproducible.

**Comment by BluSunrize** [comment]
I /hope/ I've finally fixed this one for version 1.1.8 =P

**Comment by Andri92** [comment]
So it was this all along! :P 1.1.8 fixed this for me, thank you so much for fixing it, I just couldn't go without my awesome looking cloak :D

**Comment by BluSunrize** [comment]
The fix for this isn't pretty and not what I had in mind, but I'm glad it works now :D
