### ISSUE TITLE
Singleplayer server stopping responding while generating a witching gadgets village house... I think?

### ISSUE THREAD

**Issue by BBoldt** [BluSunrize/WitchingGadgets#52]
This might be a bit hard to explain, but I have someone who confirmed the bug stopped happening when witching gadgets was removed.

The problem:
The world stops responding to input, as if you are desynced from a server, except it's in single player. Can't interact with blocks, break blocks, etc. Chunks stop loading.

The log:
http://pastebin.com/L86qaNV7
(There is lots of quivermob spam, but that is not related to this issue)

The versions:
Forge 1403
Witching Gadgets 1.1.6
Traveller's Gear 1.16.3

Sorry if I don't have much more information for you, this issue is a bit difficult to reproduce. If I get the chance I'll see if I can a more specific log.

**Comment by BluSunrize** [comment]
"com.scottkillen.mod.koresample.common.block.SlabBlock.func_149691_a(SlabBlock.java:59) "

You might want to report that to @ScottKillen

**Comment by ScottKillen** [comment]
That part is log spam from NEI when it catches and handles an exception
caused in Ancient Trees when NEI tries to get a subblock that doesn't
exist. It is properly handled in NEI, but still dumped to the log.
