### ISSUE TITLE
Shift + F

### ISSUE THREAD

**Issue by Hyperion1981** [BluSunrize/WitchingGadgets#55]
When anyone press's Shift+F the whole server crash? Don't suppose you know of a quick fix? I really don't want to remove this mod.. I LOVE this mod. Below is the crash report. Let me know if you need more..

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 5/23/15 9:39 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at witchinggadgets.common.items.tools.ItemPrimordialGlove.setSetGems(ItemPrimordialGlove.java:78)
    at witchinggadgets.common.gui.ContainerPrimordialGlove.func_75134_a(ContainerPrimordialGlove.java:120)
    at net.minecraft.entity.player.EntityPlayer.func_70106_y(EntityPlayer.java:1495)
    at net.minecraft.world.World.func_72900_e(World.java:1848)
    at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:443)
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:974)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:162)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 2.6.32-504.8.1.el6.x86_64
    Java Version: 1.7.0_75, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3621278376 bytes (3453 MB) / 4225236992 bytes (4029 MB) up to 4225236992 bytes (4029 MB)
    JVM Flags: 10 total; -Xincgc -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:PermSize=64m -XX:MaxPermSize=512m -Xmx4096M -Xms4096M -XX:+CMSClassUnloadingEnabled -XX:+CMSClassUnloadingEnabled
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1236 Cauldron-MCPC-Plus vgit-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1236 10 mods loaded, 10 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1236} [Forge Mod Loader](custom.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1236} [Minecraft Forge](custom.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WitchingGadgetsCore{1.1.7} [Witching Gadgets Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicHorizons{1.1.1} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TravellersGear{1.16.3} [Traveller's Gear](TravellersGear-1.7.10-1.16.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WitchingGadgets{1.1.7} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 3 / 50; [EntityPlayerMP['The_Privacy'/194, l='Thaumcraft4221', x=512.83, y=95.00, z=403.67](The_Privacy at 512.833677774576,95.0,403.6720116125887), EntityPlayerMP['Zadqwee'/444, l='Thaumcraft4221', x=-790.58, y=71.00, z=650.14](Zadqwee at -790.5771680814211,71.0,650.1425188866092), EntityPlayerMP['Myke776'/720, l='Thaumcraft4221', x=-784.90, y=71.00, z=649.73](Myke776 at -784.8955157507942,71.0,649.727118467537)]
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Hyperion1981** [comment]
I just remembered...Shift+F is the command to remove a foci from a wand. Maybe there are conflicting because there the same key?

**Comment by BluSunrize** [comment]
No idea what exactly happened there, but it might be fixed in the upcoming 1.1.8
