### ISSUE TITLE
Crashing after putting wrong items into the Primal Glove!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [BluSunrize/WitchingGadgets#56]
So, by accident I apperently opened up the primal glove GUI (shift + k) even though I hadn't researched it yet.

I didn't know what it was, and was starved for space, so I put dirt, cobblestone and sand into it. Back in my base I tried to open it and it crashes: http://hastebin.com/dexijinebu.coffee

Now I can't open it anymore. Every time it crashes. What if I want to use it down the road?

Any way to delete the stuff put into it, for example with NBTExplorer?

Edit: Okay, that's solved. Had to cheat in the Glove, shift+right click to open up the GUI and then I could open it up with shift+k again.

**Comment by BluSunrize** [comment]
Yeah, I didn't check to see if the player was actually carrying the glove when opening the inventory. My mistake, sorry x3
Will be fixed in 1.1.8
