### ISSUE TITLE
Crystal Capsules now broken in a slightly different way

### ISSUE THREAD

**Issue by Azutte** [BluSunrize/WitchingGadgets#57]
Tested only with tinker's construct tanks.

[Have a very slightly demonstrative album](http://imgur.com/a/esGFq). Dumping in a tank empties the entire stack of capsules. I threw them on the ground and switched into survival mode to determine that they were in fact supposed to stack (by picking them up again), clicked into tank. 

I note that this DOESN'T happen when you click capsules onto the ground. But ALSO -- not sure if relatedly -- at the same time, while you can capsule fluids off the ground, it seems that you cannot target a fluid that is ON a tank (by targeting the tank) unless said tank is empty. You cannot pick up the fluid by targeting air through it, you cannot pick it up by sneaking and targeting the tank.

A thought as to what's going on: Minetweaker returns the name of the resulting "empty" crystal capsule(s) (post- emptying one or more into a tank) as "WitchingGadgets:item.WG_CrystalFlask.withTag({})".

**Comment by BluSunrize** [comment]
probably fixed in version 1.1.9. The thing about targeting the tank through the fluids I can't fix easily, because fluids are not targetable.
