### ISSUE TITLE
Suggestion: New Explosives

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [BluSunrize/WitchingGadgets#59]
Almost every techmod, magicmod, whathaveyoumod add new items, blocks, tools, etc. but strangely almost none of them add any new explosives to the game.

I kinda want to have more choices besides TNT. Bigger, smaller, better, different, anything, really :).

New kaboom is gud!

**Comment by BluSunrize** [comment]
You suggested that on every mod's issue tracker ever. No is the answer. Metallurgy and Tinkers have explosives. Go play with those.
I would go so far as to explain that it doesn't fit the style of WG, but you simply copy and pasted this everywhere, so nevermind.

**Comment by Unrepentant-Atheist** [comment]
You don't say, Sherlock..... I'm not allowed to make multiple same suggestions of mods I use where I think an item like that would maybe fit, because....?

I'm sure all the other mod authors watch all the possible minecraft mods on GitHub, like yourself, because anything else simply is incomprehensible.

Then again you explained it doesn't fit WG's style, so that's fine with me.
