### ISSUE TITLE
Crash when viewing the aspects of certain items

### ISSUE THREAD

**Issue by Revemohl** [BluSunrize/WitchingGadgets#6]
Scanning something with the Thaumometer or holding shift while hovering the cursor over them (only one I've found so far are ferrous ingots and blocks, from Thermal Foundation, it's likely that items made with them also crash) seems to crash the game, with a spammy error log: http://pastebin.com/LTkwxgWq
I've also noticed this makes it so signalum ingots, invar ingots, enderium ingots and lumium ingots (all from Thermal Foundation as well) can't be scanned ("nothing can be learned from this").

Removing Witching Gadgets or turning off the mod's custom native clusters makes everything work properly again. Running all latest versions, as can be seen in the crash log.

**Comment by BluSunrize** [comment]
No clue as to why this happens, but v1.0.3 completely removes any aspects added to other mods, so that might help.

**Comment by Revemohl** [comment]
Doesn't seem to have fixed it, I'm still getting the same crash log from ferrous ingots. In fact, now it seems to be happening with ingots from every ore that gets a cluster from Witching Gadgets, or at least both from Thermal Foundation and Tinker's Construct.
Another side-effect is that the aspects from TF's ores that get clusters have disappeared in 1.0.3 as well (once again the "nothing can be learned from this").

**Comment by BluSunrize** [comment]
It seems quite obvious that my clusters are to blame, although I currently cannot fathom how .~.

**Comment by BluSunrize** [comment]
V1.0.4 allow you to disable transmutations now, this should fix the crash and /might/ fix the lack of aspects.

**Comment by Revemohl** [comment]
Yeah, looks like disabling nuggets does fix both problems, and the new spinning wheel is much lighter. Thanks!
