### ISSUE TITLE
A question, and a suggestion

### ISSUE THREAD

**Issue by Sunconure11** [BluSunrize/WitchingGadgets#66]
1. Would it be possible to add affinities and aversions to gems via Minetweaker? I see this mod has some Minetweaker support.
2. What will become of the angel's armor, found in the files?

**Comment by BluSunrize** [comment]
1. I'm currently very focused on other proejcts atm. If I go back to working on WG, I'll take it into consideration.
2. Angel and Demon armor used to endgame armor before I went for primordial. It will not come back in WG.

**Comment by BluSunrize** [comment]
Actually I'm gonna leave this open as a reminder.

**Comment by ghost** [comment]
They could be late midgamet sets with special effects? Like botania cloaks of virtue and sin?

**Comment by BluSunrize** [comment]
No, I will not add them back into WG.

**Comment by BluSunrize** [comment]
There we go, all done! Minetweaking for gem affinities will be in the next release of WG =3
