### ISSUE TITLE
Thaumic Sauna Stove fps drop

### ISSUE THREAD

**Issue by ghost** [BluSunrize/WitchingGadgets#69]
Hello, I been using your mod in a server and I realized ever time my friend did try to make the Thaumic sauna stove to work (it does not seen to be working everywhere, it works fine in my desert but not in his forest, we did try in some other places with random results) it seen to be dropping the fps of anyone around it.

**Comment by BluSunrize** [comment]
Yep I keep getting that report and I can't replicate it on my end. I'm not saying it's not happening but I also don't know how to fix it since i can't properly investigate it.

**Comment by inklesspen1rus** [comment]
That's happening when Sauna taking water and each 10 minutes when sauna wasting water and taking again
I'm using fluid pipe to fill sauna, it can cause this problem
When I place sauna without pipes it causes fps drop until I fill it with water bucket

**Comment by BluSunrize** [comment]
This mod has not been maintained for years. This will not be addressed.
