### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by RedsaphirCZ** [BluSunrize/WitchingGadgets#7]
I tried to take picture of vanilla doors, used your "magical camera" with shiftclick on doors. Don't know if openeye will send you this,so i post it here, just for sure.
Here is crash report: http://pastebin.com/2FVRA0ta

**Comment by BluSunrize** [comment]
Never seen that before. It apparently crashed when trying to write the crashreport. No idea what causes this...

**Comment by EndermanParty** [comment]
I have had a crash with your Iconograph as well, Just pulling it out of my hotbar (putting it into my hands) causes an instant crash..

**Comment by EndermanParty** [comment]
however, I use optifine.. I have a horrible PC

**Comment by BluSunrize** [comment]
I'm not sure if this is relevant anymore, so I'll close it.
