### ISSUE TITLE
Misssing Blocks and Items on dedicated servers

### ISSUE THREAD

**Issue by midorlo** [BluSunrize/WitchingGadgets#73]
Problem: Clients cannot connect to dedicated Forge server running WitchingGadgets-1.7.10-1.1.9. Clients do can connect to LAN-SMP worlds though.

Scenario:
Successfully connected 1 Client to a LAN-SMP-Client. Cloned the whole compilation of /mods/ and /config/ to an instance of minecraft_server.jar running under Forge 1492 (1448 tested as well). This is what a clients gets when trying to connect:

http://pastebin.com/raw.php?i=bNAzx7hS

**Comment by midorlo** [comment]
Adding more information (do you preffer github for managing issues?):
This is a language specific issue. 2 Clients not having the same language cannot connect to each other. Any non english client will not be able to join servers at all.

**Comment by BluSunrize** [comment]
Yeah. I know what this one is about. This bug must have been in since I started writing this. Will be fixed for the new release.
