### ISSUE TITLE
MineTweaker support, is it released?

### ISSUE THREAD

**Issue by Not-February** [BluSunrize/WitchingGadgets#77]
Hello, I do not know if you are still actively checking or working on this mod, but I thought I would bring up something that I've been having issues with...

I've been using MineTweaker in a private modpack project for a while now, and when I recently added Witching Gadgets to the mods list, I was delighted to see that there is in-built support for MT on the wiki, notably with the gemcutting. It's even listed on the forum page for your mod that the MineTweaker support is a thing.

I had a long thing written up about how I couldn't get it to work before I checked the dates on the file I downloaded vs. the commit on GitHub that apparently added the support, and at this point I believe there is an inconsistency regarding the currently public version of the mod and the documentation available.

The most recent file I can find for downloading your mod is on Curse or CurseForge, and that was put there as v1.1.9 - back in May. The MineTweaker support appears to have only been added in sometime in July, if Github is anything to go by.

Is there anywhere I could download a pre-compiled version of Witching Gadgets that has the MineTweaker support implemented? Or is that just not released at this time?

If it isn't available, it's kind of odd that the documentation is already available, and that it's promoted as a feature on your forum post. I'm hoping that I'm just missing something obvious with all of this, but I thought I would bring it up just in case I'm not.

**Comment by Yulife** [comment]
The gem cutting support hasn't been released yet, all the other stuff is doable though.

**Comment by Not-February** [comment]
D'oh. Figures. The gemcutting was the one thing I really wanted to add some new options for, haha. Guess I'll wait on that for now then.

**Comment by Yulife** [comment]
It is now.
