### ISSUE TITLE
Dupe bug with hungry bag

### ISSUE THREAD

**Issue by Kazzamkablam** [BluSunrize/WitchingGadgets#79]
Running on version 1.1.9 (1.7.10)

Works with inventory tweaks installed
step 1: Open bag
step 2: Assign anything using number keys from your inventory to bag slot
step 3: Close bag
step 4: Right click your bag slot again and it dupes it.

**Comment by BluSunrize** [comment]
Which version of WG are you running?

Edit: Nevermind, fixed this one already, just not in a built version. Will be in the next one.

**Comment by Kazzamkablam** [comment]
Running on version 1.1.9 (1.7.10)
