### ISSUE TITLE
Crash on Opening Thaumanomicon Aspects Entry

### ISSUE THREAD

**Issue by SciFiz** [BluSunrize/WitchingGadgets#8]
v1.0.5 causes a stackoverflow on opening the Aspects entry of the Thaumanomicon of my SSP. However I can't repeat it in a creative test world. The .thaum file is 11kb, compared to the 5kb of the creative world with cheat sheet.

v1.0.1 doesn't have this issue.

[Pastebin log](http://pastebin.com/rRv6vZ6k)

**Comment by BluSunrize** [comment]
Yeah that's been tackled multiple times now. Update your version and disabled nugget transmutations.
