### ISSUE TITLE
Rose Vines don't spread

### ISSUE THREAD

**Issue by Shahelion** [BluSunrize/WitchingGadgets#82]
The Thaumonomicon entry leads one to believe that they spread by making more of themselves, but I've had this one sitting in the same place for real-time days now, and no more have appeared. It's in the middle of a patch of grass, out in the open, in a taiga biome.

**Comment by Shahelion** [comment]
Is it intended that they don't spread on their own? Am I just supposed to make more, or am I missing something?

**Comment by vdrake77** [comment]
They grow up things.  Similar to vines on walls.  It's not explained well, but they don't spread 'out'.  Use shears, put it on the ground near the base of a wall.  It'll start growing up them, and you can shear those vines and place them else where, so the growth is exponential.

**Comment by Shahelion** [comment]
Hindsight is 20/20 lol thank you.
