### ISSUE TITLE
ModPack with WitchingGadgets gives State Engine Error

### ISSUE THREAD

**Issue by VincentRuoka** [BluSunrize/WitchingGadgets#86]
When I add Witching Gadgets to my ModPack I can no longer open any World or close my MC instance. It gives me this Error while trying to start a world: 
![1e105b7bc001f4466c5c5da777d4698b](https://cloud.githubusercontent.com/assets/8927845/10453560/73ec9842-71ad-11e5-8d77-ee0b8a1dff54.png)
Also if that's helpful, my modcount in MC adds +2 for WitchingGadgets instead of +1 or is it more then on mod in the *.jar?

**Comment by BluSunrize** [comment]
Yes, WG contains a coremod, that's why it shows +2. That image you showed is a generic error message. I'll need to see the whole log (on pastebin or similar) to help you.

**Comment by VincentRuoka** [comment]
http://pastebin.com/DgMU9LgE

**Comment by BluSunrize** [comment]
go into the config, disable transmutations.
