### ISSUE TITLE
Permission To Transport

### ISSUE THREAD

**Issue by ZH-heren** [BluSunrize/WitchingGadgets#94]
Thank u for making zhe WitchingGadgets.As I am making localization for it,u may know I am from China.We also hava a fornm named MCBBS(http://www.mcbbs.net/forum.php).
Most of players here don't go to the MCF for their pour english and bad network.Here I ask for ur permission to transport ur mod to zhe MCBBS.If u permiss, I'll post a thread in chinese there with zhe url of ur raw thread.Thank u very much.

**Comment by Mrkwtkr** [comment]
So u did that out of your vanity? At first, I doubt if the localization was made by yourself. Next, u don't have to use the same sentence pattern as me to ask for permission. What u did will lead to misunderstanding. Last but not least, it is 'the', not 'zhe'.

**Comment by BluSunrize** [comment]
@Mrkwtkr Don't bash him for his spelling, English is clearly not his first language.

@ZH-heren If you provide the links to the curseforge downloads, that is fine by me. If you reupload the files to a different host, that would be unkind.
You have my permission to provide that page with a proper thread and links to WG.

**Comment by Mrkwtkr** [comment]
Not bash:P 
Im in MCBBS, where he is using my localization without my permission.

**Comment by ZH-heren** [comment]
I am very very sorry for my behavior.Here,I beg your pardon with my most sincere apology.Sorry

**Comment by Mrkwtkr** [comment]
其实没什么大事，我群里人艾特我给我看了这个issue，然后根据前端时间黑猫联系我的大致知道是你，有人都把你qq人肉出来了。。。发这种授权最好说清楚本地化来源，毕竟我当时也是辛辛苦苦弄出来的，不反对你搬运发帖什么的，引用别人的东西一定要注明来源。

**Comment by Mrkwtkr** [comment]
另外你搬运贴里面几个图挂了，去补下吧= =

**Comment by ZH-heren** [comment]
知道了，谢谢

**Comment by ZH-heren** [comment]
对了，好像这个mod和神秘工匠有冲突。我怎么一打开，过一会就闪退了
