### ISSUE TITLE
Ore Dictionary issues?

### ISSUE THREAD

**Issue by Shahelion** [BluSunrize/WitchingGadgets#98]
It seems that Witching Gadgets is somehow seeing TiCon Aluminum oreberries as valid nuggets even after they are removed from the nugget oreDict entry. This seems to imply that WG is reading the oreDict on startup, but isn't rechecking later to allow for possible modifications.

For more information: https://github.com/SlimeKnights/TinkersConstruct/issues/1820#issuecomment-160433322

**Comment by BluSunrize** [comment]
See my comment on there then.

**Comment by Robijnvogel** [comment]
Do with this whatever you like then.
Some people who like to break the rules, would love it if you made this work.

+I hope that it will set an update chain in motion that will ultimately result in the support of Infernal (Blast) Furnace recipes in MineTweaker and ModTweaker.

**Comment by BluSunrize** [comment]
I'm continuing thsi discussion on the tinkers issue, in case you hadn't noticed. Since this is more boni's oredict being derped than my compat.

**Comment by Robijnvogel** [comment]
Es Bueno
